### PR TITLE
chore(site): fix broken rule menu links

### PR DESCRIPTION
**Pull request by ota-meshi**
Clicking on the rules menu on the new site shows a 404 page.
This PR fixes that broken link.

### CODE REVIEW

**Comment by vhoyer** [comment]
do both middle and left click open the page correctly?

**Comment by vhoyer** [comment]
anyway, that constant is used only on one other place, if we are removing it from `rulesFromSidebar`, we should also remove it from the `constants` file and just use it directly on the other file, can you fix it?

**Comment by ota-meshi** [comment]
> do both middle and left click open the page correctly?

Yes.

> we should also remove it from the constants file and just use it directly on the other file, can you fix it?

I removed constants.ts.

**Review by vhoyer — APPROVED** [review]
Thanks for the contribution

**Pull request merged**
